### ISSUE TITLE
[3d-print]: Raymond 3D print

### ISSUE THREAD

**Issue by RaymondWei78** [Amp-Lab-at-VT/print-queue#10]
### Contact Details

wraymond03@vt.edu

### About Your Print

Fiber optic adaptor for testing convex lens focusing beams. 
[FiberTestingAdaptor.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11791350/FiberTestingAdaptor.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
I'll see if I can start this tonight!

**Comment by Forsyth-Creations** [comment]
@RaymondWei78 I'm getting this printed at my place and will drop it off in-lab. I couldn't remember if I had re-loaded the filament in-lab on the P1P, so this seemed like the quickest solution. 

Two quick things:
1. I'd like to train you to start prints at some point, that way you can have unimpeded access. 
2. I don't want us to make a habit out of printing things for other labs. However, you've put a lot of work in for us with the CNC, so I'd like to return the favor. 

Print has been started, and I will try to deliver later this morning!

**Comment by RaymondWei78** [comment]
I’d really appreciate that! Please let me know how you plan on making that happen, thanks Henry!

**Comment by Forsyth-Creations** [comment]
I believe I finished this
