### ISSUE TITLE
[3d-print]: SMD component magazine

### ISSUE THREAD

**Issue by devincress** [Amp-Lab-at-VT/print-queue#12]
### Contact Details

dcress94@vt.edu

### About Your Print

SMD component magazine w/ rail for the lab as requested by Richard. 65x67x15mm and 120x70x20mm. Default print settings should be fine.

https://www.thingiverse.com/thing:3952021

[Compliant_SMD_Magazine_15_2.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/12796950/Compliant_SMD_Magazine_15_2.zip)

[Rail_120-5.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/12796987/Rail_120-5.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
how many?

**Comment by Forsyth-Creations** [comment]
For viz, I've started printing this in the lab. I figure we can print more if we need them, and the files will be available. The ETA is about 5 hours

**Comment by Forsyth-Creations** [comment]
@devincress if you're happy with what was printed, please feel free to close this issue

**Comment by Forsyth-Creations** [comment]
I know these have been printed, so I am going to close this issue. @devincress please close these issues in the future to provide better traceability
