### ISSUE TITLE
[3d-print]: Test Rig for InspireFly

### ISSUE THREAD

**Issue by jtjagoda** [Amp-Lab-at-VT/print-queue#15]
### Contact Details

jtjagoda@vt.edu

### About Your Print

Length: 100mm
Width: 100mm
Height: 19mm

[Part1.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/13064076/Part1.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This is printing right now in the lab. There seems to be a potential duplicate submission from your team. If you wanted to request two of the same part, just add a quantity to the ticket. If this was a mistake in duplicate submissions, please close the other ticket :)
