### ISSUE TITLE
[3d-print]: Prints for Stylophone

### ISSUE THREAD

**Issue by jiviteshkuk26** [Amp-Lab-at-VT/print-queue#16]
### Contact Details

jiviteshkuk26@vt.edu

### About Your Print

Description
->Lower Body, (202x80x13.60) mm, Black
->Upper Body, (202x80x12.50) mm, Black
->Filler Plate, (199x35.50x1.9) mm, Red
->Face Plate, (202x38.50x3.9) mm, Black
->Stylus, (100x5x5) mm, Black, Could you maybe add magnets to the flat side of this like the QR codes?

Files:
[3D Print Files.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/13461953/3D.Print.Files.zip)

Thank You!

### Material

PLA

**Comment by Forsyth-Creations** [comment]
@jiviteshkuk26 I did print this. If this is acceptable, please close this issue :) I will close in a week if you don't respond

**Comment by jiviteshkuk26** [comment]
> @jiviteshkuk26 I did print this. If this is acceptable, please close this issue :) I will close in a week if you don't respond

I kept it open since I wanted to print everything again as most of the current body broke :(. I will close it for now and print it again after the break. Thank You, Have Fun!
