### ISSUE TITLE
[3d-print]: InspireFly Test Rig

### ISSUE THREAD

**Issue by jtjagoda** [Amp-Lab-at-VT/print-queue#17]
### Contact Details

jtjagoda@vt.edu

### About Your Print

10cm *10cm*5.7cm
[TestRig2.0.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14250461/TestRig2.0.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
@jtjagoda Sorry this slipped under my radar. Do you still need this part?

**Comment by jtjagoda** [comment]
No worries, I don’t need it anymore. Thank you though.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
