### ISSUE TITLE
[3d-print]: 

### ISSUE THREAD

**Issue by StephenWelch** [Amp-Lab-at-VT/print-queue#18]
### Contact Details

stephenwelch@vt.edu

### About Your Print

Dimensions: ~50mm square

[T-nut_M3_x12.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14353724/T-nut_M3_x12.zip)
 From Thingiverse:

> Print very slow around 10 mm/s with a little (if single nut) or no cooling (batch)
> For best results and strength set in Cura:
Top Layers: 1000
Bottom Layers: 0
Top/Bottom Pattern: Concentric

### Material

PLA

**Comment by Forsyth-Creations** [comment]
@StephenWelch sorry this slipped under my radar. Do you still need this?

**Comment by StephenWelch** [comment]
I ended up printing them myself, thank you though!
