### ISSUE TITLE
[3d-print]: Inspirefly Prints

### ISSUE THREAD

**Issue by Tejas-Vinod** [Amp-Lab-at-VT/print-queue#20]
### Contact Details

tejasv22@vt.edu

### About Your Print

Test Rig 2.1
100 x 100 x 17.27

Mirror Mount
22.86 x 14.478 x 28.194

[Inspirefly prints.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14629070/Inspirefly.prints.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This print has been started in-lab. ETA is 3 hours

**Comment by Forsyth-Creations** [comment]
Finished and waiting in-lab. Please close this issue once you have picked up your part
