### ISSUE TITLE
[3d-print]: MDE S24-06 Valve Bracket

### ISSUE THREAD

**Issue by taylormk19** [Amp-Lab-at-VT/print-queue#21]
### Contact Details

taylormk@vt.edu

### About Your Print

33.8mm x 12.4mm x 23.5mm
[Valve Bracket Print.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14644098/Valve.Bracket.Print.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This print has been started in-lab. ETA is 3 hours

**Comment by Forsyth-Creations** [comment]
Finished and waiting in-lab. Please close this issue once you have picked up your part
