### ISSUE TITLE
[3d-print]: MDE S24-06 Enclosure

### ISSUE THREAD

**Issue by taylormk19** [Amp-Lab-at-VT/print-queue#22]
### Contact Details

taylormk@vt.edu

### About Your Print

171 x 140 x 64
[Enclosure.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14663103/Enclosure.zip)

### Material

PLA

**Comment by taylormk19** [comment]
It's been almost a week since this request was made. Are there any updates on the print?

**Comment by Forsyth-Creations** [comment]
![image](https://github.com/Amp-Lab-at-VT/print-queue/assets/33364183/6a547d75-383a-4111-b4ae-6b3043545cbc)

For the record, the pins you've designed here are most likely going to break when 3D printed without extra support. Working on getting this print started for you now

**Comment by taylormk19** [comment]
They don't need to support much weight. Something on the order of less than 100 grams. However, if you believe they will break when printing then that is something I will consider for printing next time.
