### ISSUE TITLE
[3d-print]: MDE S24-06 Pump Bracket

### ISSUE THREAD

**Issue by taylormk19** [Amp-Lab-at-VT/print-queue#23]
### Contact Details

taylormk@vt.edu

### About Your Print

62 x 46 x 26 mm
[Vacuum Pump Bracket.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14675729/Vacuum.Pump.Bracket.zip)

### Material

PLA

**Comment by taylormk19** [comment]
Is there any update on this print?

**Comment by Forsyth-Creations** [comment]
This print is complete and is waiting for you in-lab. Let me know if there are any issues, and please close this ticket after pickup!

**Comment by taylormk19** [comment]
Everything looks good. Thank you!
