### ISSUE TITLE
[3d-print]: MDE S24-06 Enclosure

### ISSUE THREAD

**Issue by taylormk19** [Amp-Lab-at-VT/print-queue#28]
### Contact Details

taylormk@vt.edu

### About Your Print

160 x  140 x 64 mm
[Enclosure.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14775250/Enclosure.zip)

### Material

PLA

**Comment by taylormk19** [comment]
@Forsyth-Creations How soon can this be printed?

**Comment by Forsyth-Creations** [comment]
This print is complete and is waiting for you in-lab. Let me know if there are any issues, and please close this ticket after pickup!

**Comment by taylormk19** [comment]
Everything looks good. Thank you!
