### ISSUE TITLE
[3d-print]: MDE S24-06 Flow Cell

### ISSUE THREAD

**Issue by taylormk19** [Amp-Lab-at-VT/print-queue#29]
### Contact Details

taylormk@vt.edu

### About Your Print

50 x 50 x 13 mm
[Flow Cell.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14775268/Flow.Cell.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This print is complete and is waiting for you in-lab. Let me know if there are any issues, and please close this ticket after pickup!

**Comment by taylormk19** [comment]
Everything looks good. Thank you!
