### ISSUE TITLE
[3d-print]: MDE IEEE Robot team - limit switch slider mount

### ISSUE THREAD

**Issue by Initializing** [Amp-Lab-at-VT/print-queue#3]
### Contact Details

leoren@vt.edu

### About Your Print

Dimension: 65*26*10 (mm)
[Limit Switch sliding mount.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11092383/Limit.Switch.sliding.mount.zip)

### Material

PLA

**Comment by Initializing** [comment]
Sorry, the size is 65 - 26 - 10 (mm)

**Comment by Forsyth-Creations** [comment]
I'll get this printing right now! Having someone check the bed to make sure it's ready to go. Thanks for using this process! You're the first one, so congrats!

**Comment by Forsyth-Creations** [comment]
Print has been started in the lab. Plus or minus any unforeseen issues, it should be ready within the hour.

**Comment by ethanjamesauto** [comment]
Print is ready

**Comment by Initializing** [comment]
Part collected. Good quality. Thanks for all the help!
