### ISSUE TITLE
[3d-print]: S24-11 Arduino Due Board

### ISSUE THREAD

**Issue by Asena888** [Amp-Lab-at-VT/print-queue#31]
### Contact Details

jennyli@vt.edu

### About Your Print

Size around 4 x 2.1 inches
I do not care what material is used. This is for senior design.
[BSBLanCase.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14805734/BSBLanCase.zip)

### Material

Don't Know

**Comment by Forsyth-Creations** [comment]
This print is complete and is waiting for you in-lab. Let me know if there are any issues, and please close this ticket after pickup!

**Comment by Asena888** [comment]
I picked up the orange arduino due print with the lid. In the zip there is 3 file another one called BSBLanCase.3mf. Was it printed and I missed it in the Lab or not printed?
