### ISSUE TITLE
[3d-print]: NEBP Video Payload Camera Mount

### ISSUE THREAD

**Issue by jiviteshkuk26** [Amp-Lab-at-VT/print-queue#32]
### Contact Details

jiviteshkuk26@vt.edu

### About Your Print

~30x30x30 mm
[camera_mount.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14809614/camera_mount.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This print is complete and is waiting for you in-lab. Let me know if there are any issues, and please close this ticket after pickup!

**Comment by jiviteshkuk26** [comment]
Thank You!
