### ISSUE TITLE
[3d-print]: Test Rig for CubeSat

### ISSUE THREAD

**Issue by Tejas-Vinod** [Amp-Lab-at-VT/print-queue#34]
### Contact Details

tejasv22@vt.edu

### About Your Print

100 x 44 x 79mm
[Testrig_nowall.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14844606/Testrig_nowall.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This is printed and awaiting for you in-lab. Please close this issue after pickup
