### ISSUE TITLE
[3d-print]: S24-11 Arduino Due Box

### ISSUE THREAD

**Issue by Asena888** [Amp-Lab-at-VT/print-queue#35]
### Contact Details

jennyli@vt.edu

### About Your Print

Size around 4 x 2.1 inches
I do not care what material is used. This is for senior design. I did submit this last time however, I don't believe the attached file box now was printed. If I'm mistaken please let me know. Thanks
[BSBLanCase (1).zip](https://github.com/Amp-Lab-at-VT/print-queue/files/14894415/BSBLanCase.1.zip)

### Material

Don't Know

**Comment by Forsyth-Creations** [comment]
This is printed and awaiting for you in-lab. Please close this issue after pickup
