### ISSUE TITLE
[3d-print]: vibration table mount 1

### ISSUE THREAD

**Issue by jtjagoda** [Amp-Lab-at-VT/print-queue#37]
### Contact Details

jtjagoda@vt.edu

### About Your Print

50.8 x 25.4 x 63.5 mm
[radius_clamp.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/15025383/radius_clamp.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Printing now. Should be ready in the next two hours. Please close this issue upon pickup

**Comment by Forsyth-Creations** [comment]
Printed and waiting in-lab
