### ISSUE TITLE
[3d-print]: vibration table fixture 2

### ISSUE THREAD

**Issue by jtjagoda** [Amp-Lab-at-VT/print-queue#38]
### Contact Details

jtjagoda@vt.edu

### About Your Print

2.54 x 50.8 x 63.5 mm
[end clamp.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/15025422/end.clamp.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Printing now. Should be ready in the next two hours. Please close this issue upon pickup

**Comment by Forsyth-Creations** [comment]
Printed and waiting in-lab
