### ISSUE TITLE
[3d-print]: Mirror Mount fixed design

### ISSUE THREAD

**Issue by Tejas-Vinod** [Amp-Lab-at-VT/print-queue#39]
### Contact Details

tejasv22@vt.edu

### About Your Print

[MirrorMount_22x16x26mm.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/15068062/MirrorMount_22x16x26mm.zip)

22x16x26mm

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Printing now. Should be ready in the next two hours. Please close this issue upon pickup

**Comment by Forsyth-Creations** [comment]
Printed and waiting in-lab
