### ISSUE TITLE
[3d-print]: VT CRO Sweeper Arm

### ISSUE THREAD

**Issue by MinMaxolotl** [Amp-Lab-at-VT/print-queue#4]
### Contact Details

kmaxwell21@vt.edu

### About Your Print

Hey there! This print should be the same dimensions as in the file and should have a 25% fill. 

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Thank you for submitting this ticket! Staff will look at it tomorrow and get things printed!

**Comment by Forsyth-Creations** [comment]
@MinMaxolotl I don't see a part file. Did you attach it? I know you messaged me the solidworks part file through Discord, but I need the STL or 3MF files to 3D print

**Comment by MinMaxolotl** [comment]
Hm, I thought there was a file attached. It should be here. Apologies! I wont make this mistake again!

[SweeperArm.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11115974/SweeperArm.zip)

**Comment by Forsyth-Creations** [comment]
Sweet, I'll get this started sometime tomorrow!

**Comment by Forsyth-Creations** [comment]
@MinMaxolotl this is still just the Solidworks file. The Amp Lab does not make a habit of going in and grabbing your mesh files from the part. Please submit them in either an STL or 3MF format. Thank you!

**Comment by MinMaxolotl** [comment]
Ahh once again I apologize. I am unfamiliar with making prints, here is HOPEFULLY the correct version. 
[SweeperArm.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11117684/SweeperArm.zip)
@Forsyth-Creations

**Comment by Forsyth-Creations** [comment]
Printing in-lab right now

**Comment by Forsyth-Creations** [comment]
I don't see this in-lab. Was it picked up? If so, @MinMaxolotl please mark this issue as closed

**Comment by MinMaxolotl** [comment]
Sorry! Just saw this. Yeah I've been coming in and picking up the prints when I get the notifications they are complete. Thank you!

**Comment by Forsyth-Creations** [comment]
> Sorry! Just saw this. Yeah I've been coming in and picking up the prints when I get the notifications they are complete. Thank you!

@MinMaxolotl 

No problem! Just to keep the loop closed, if you are picking up the prints, make sure to update the status of the issue! Thank you for helping us test this new 3D printing process lol
