### ISSUE TITLE
[3d-print]: Upper knob housing for smart speaker project

### ISSUE THREAD

**Issue by RaymondWei78** [Amp-Lab-at-VT/print-queue#40]
### Contact Details

wraymond03@vt.edu

### About Your Print

Hey Henry, the file attached is the upper housing of the remote to my smart speaker project. Inside the zip is a STL with 4 separate parts in it, and a screenshot of what it looks like. It would be incredible if you could help me print the piece labeled 2 in the screenshot in white, as it is meant to be used as a reflective light diffuser, and 1, 3, and 4 in black as they have to block light from leaking. if it is too much trouble, everything can just be done in white and I will figure out a way to prevent light leakage. As everything is meant to snap together with other pieces, it would be great if the print could also be done in the highest precision and infill rate possible. Thank you so much!

[RW Knob Print.zip](https://github.com/user-attachments/files/16627516/RW.Knob.Print.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
@RaymondWei78 would you still like this to be printed?
