### ISSUE TITLE
[3d-print]: Camera Housing

### ISSUE THREAD

**Issue by NateHernandez1** [Amp-Lab-at-VT/print-queue#41]
### Contact Details

natehernandez@vt.edu

### About Your Print

camera casing for inspireFly
Bot dimensions: 34x34x8.5mm
Top dimensions: 34x34x18mm
[camhousing.zip](https://github.com/user-attachments/files/16750515/camhousing.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Hey Nate! This is printing in-lab for you now. Should be ready for you in the next few hours
