### ISSUE TITLE
[3d-print]: Site Map

### ISSUE THREAD

**Issue by devin-hr** [Amp-Lab-at-VT/print-queue#42]
### Contact Details

devinhr@vt.edu

### About Your Print

file needs to be scaled down to 185.7mm x 85.7mm x 5.6mm or to the largest pint area
[NSB SITEMAP - 3d print.zip](https://github.com/user-attachments/files/16875581/NSB.SITEMAP.-.3d.print.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
This is printing for you in the lab, and will be ready in the next few hours. However, you should review your model. I believe there is a mesh error in your site model:
![Screenshot 2024-09-05 162509](https://github.com/user-attachments/assets/0cd9a7b6-86e7-4ea0-a8ec-0bd4b6b4ec5e)
