### ISSUE TITLE
[3d-print]: add on to issue 45, Car

### ISSUE THREAD

**Issue by sarahfox03** [Amp-Lab-at-VT/print-queue#49]
### Contact Details

sarahfox@vt.edu

### About Your Print

Hello!
I need five of these (sorry ) but i need a different size chassis. I have attached. If I could have these as quickly as possible, that would be awesome , for senior design. Thank you SOO much
[Car.zip](https://github.com/user-attachments/files/17633184/Car.zip)
[](url)
[smars_chassis_SL_tall_3mm.zip](https://github.com/user-attachments/files/17633193/smars_chassis_SL_tall_3mm.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Starting this on my home printer now. Should be able to churn out all five by tomorrow afternoon. Sorry for the delay!

**Comment by Forsyth-Creations** [comment]
![image](https://github.com/user-attachments/assets/92b09f59-b9b5-486f-9775-c2b1d927894b)

**Comment by Forsyth-Creations** [comment]
They're in-lab in the boxes!
