### ISSUE TITLE
[3d-print]: 

### ISSUE THREAD

**Issue by MinMaxolotl** [Amp-Lab-at-VT/print-queue#5]
### Contact Details

kmaxwell21@vt.edu

### About Your Print

43.4 mm wide, 23.4 mm long, and 32.8 mm tall. 50% fill. This is a servo mount.
[ServoMoutSW.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11132848/ServoMoutSW.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Printed, and ready/waiting for you in-lab!

**Comment by MinMaxolotl** [comment]
Thank you!
