### ISSUE TITLE
[3d-print]: F24-14 PCB Enclosure

### ISSUE THREAD

**Issue by vivanchopra** [Amp-Lab-at-VT/print-queue#50]
### Contact Details

vivc2018@vt.edu

### About Your Print

The print is of a PCB enclosure that will be used for our device. There are two STL files BD1 and BD2. BD1 contains 4 holes at the edges that are 2mm and BD2 contains similar holes and a portion that is cut on the base to have access to measure current across the device The Length is 106mm, the Width is 64.5mm and the Height is 34.5mm.
[F24_14_PCB.zip](https://github.com/user-attachments/files/17749677/F24_14_PCB.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
I'm getting this started on my home printer, and will bring it in tomorrow if all goes well!
