### ISSUE TITLE
[3d-print]: FL24-14 PCB Enclosure

### ISSUE THREAD

**Issue by vivanchopra** [Amp-Lab-at-VT/print-queue#51]
### Contact Details

vivc2018@vt.edu

### About Your Print

PCB enclosure for device. Added space for the battery holder. Length 106mm, Width 64.5mm, Height 25mm.

### Material

PLA

**Comment by vivanchopra** [comment]
[BD_1.zip](https://github.com/user-attachments/files/17757855/BD_1.zip)

**Comment by Forsyth-Creations** [comment]
I'm getting this started on my home printer, and will bring it in tomorrow if all goes well!

**Comment by Forsyth-Creations** [comment]
![image](https://github.com/user-attachments/assets/e9d343b7-d3e3-4a79-b940-3136da0a5883)
