### ISSUE TITLE
[3d-print]: VT Cookie Cutters

### ISSUE THREAD

**Issue by richgibbons98** [Amp-Lab-at-VT/print-queue#7]
### Contact Details

gricha1@vt.edu

### About Your Print

These are some test prints for VT Cookie Cutters
[El-Ultimo-Cookie-cutter-Apr-29.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11360161/El-Ultimo-Cookie-cutter-Apr-29.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
Starting this print now

**Comment by Forsyth-Creations** [comment]
@richgibbons98 I know this print finished, but it's still protocol for me to check in. How'd it turn out? If you like it, feel free to close this issue ticket :)

Rule # 6 of the print queue btw: https://github.com/Amp-Lab-at-VT/print-queue/

**Comment by richgibbons98** [comment]
It turned out great! Just waiting on the cookies at this point.

Best,
Richard Francis Gibbons III
Graduate Teaching Assistant - MDE
Virginia Tech Electrical Engineering Class of 2021
571-455-9877
***@***.***

**Comment by richgibbons98** [comment]
How do I close the issue ticket?

Best,
Richard Francis Gibbons III
Graduate Teaching Assistant - MDE
Virginia Tech Electrical Engineering Class of 2021
571-455-9877
***@***.***

**Comment by Forsyth-Creations** [comment]
When you leave a comment, you should be able to click the "Close with Comment" button, which will close the issue. I can do it, but I want you to get the exposure to it.

**Comment by Forsyth-Creations** [comment]
![image](https://user-images.githubusercontent.com/33364183/236587894-ea2c42d8-135b-442d-9c0e-c3cae157dbcb.png)

@richgibbons98

**Comment by richgibbons98** [comment]
done
