### ISSUE TITLE
[3d-print]: My very cool building idea (it has to do with electronics)

### ISSUE THREAD

**Issue by epritchard13** [Amp-Lab-at-VT/print-queue#8]
### Contact Details

epritchard@vt.edu

### About Your Print

This is a building. It would be cool to 3d print a scale model. There will be lighting installed into the building in order to take photos of the lighting and experimenting in wiring.
[cool building.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11363269/cool.building.zip)

### Material

PLA

**Comment by Forsyth-Creations** [comment]
I don't believe the comment, but I'll print it anyway

**Comment by Forsyth-Creations** [comment]
@epritchard13 Did you get this print off the bed? I would like to start @richgibbons98 print

**Comment by Forsyth-Creations** [comment]
Richard has confirmed this print has been completed, or at the very least that it was removed from the bed. Closing this issue
