### ISSUE TITLE
[3d-print]: void keyboard switch test

### ISSUE THREAD

**Issue by sakgoyal** [Amp-Lab-at-VT/print-queue#9]
### Contact Details

sakgoy2001@vt.edu

### About Your Print

I have some stl files I downloaded that I want to print. No idea what material it should be but I think any should be fine. 
since this part is small and has small details, I would prefer a high amount of precision/accuracy

total dimensions approximate: (~3.3cm x ~3cm x ~1cm)

I would like to get 4 of each of the 2 stl files please. [void_switch_test_print.zip](https://github.com/Amp-Lab-at-VT/print-queue/files/11581859/void_switch_test_print.zip)

![image](https://github.com/Amp-Lab-at-VT/print-queue/assets/19929553/7380636a-ee9e-4a9a-b650-3dc5286ba41d)
![image](https://github.com/Amp-Lab-at-VT/print-queue/assets/19929553/9a0e36e6-5599-4322-8a3b-b6dac2611f2d)

### Material

Don't Know

**Comment by Forsyth-Creations** [comment]
We've been slow to respond due to the summer, but did this get printed? Wanted to make sure so I can get it printed for you

**Comment by Forsyth-Creations** [comment]
@sakgoyal Does this still need to be printed?

**Comment by sakgoyal** [comment]
Yes please

**Comment by Forsyth-Creations** [comment]
This has been printed, and is now awaiting you in-lab. Let me know when you pick it up, and I will close out this issue!

**Comment by Forsyth-Creations** [comment]
Was this picked up @sakgoyal? Just want to confirm if I can close this

**Comment by sakgoyal** [comment]
Yep
